services:
  postgres:
    image: postgres
    container_name: pg_sql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

#  pgadmin:
#    container_name: pg_admin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - microservices-net
#    restart: unless-stopped

  mail-dev:
    container_name: mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"  # Allows root access from any host
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Empty password for root
    ports:
      - 3306:3306
    networks:
      - microservices-net
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped



networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql_data:
