name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql

      - name: Configure MySQL root user for password authentication
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'temp_password';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Set up MySQL database and permissions
        env:
          MYSQL_PWD: temp_password
        run: |
          mysql -u root -p"$MYSQL_PWD" -e "CREATE DATABASE IF NOT EXISTS geo_location;"
          mysql -u root -p"$MYSQL_PWD" -e "GRANT ALL PRIVILEGES ON geo_location.* TO 'root'@'localhost';"
          mysql -u root -p"$MYSQL_PWD" -e "FLUSH PRIVILEGES;"
          

  build:
    needs: setup-mysql
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR via SCP with SSH Key Authentication
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.204.227.9
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Utilise la clé SSH ajoutée aux secrets
          port: 22
          source: "target/*.jar"
          target: "/home/ubuntu/geolocation_api.jar"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS VM and Configure MySQL Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 43.204.227.9
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Utilise la clé SSH ajoutée aux secrets
          port: 22
          script: |
            # Arrêter l'ancienne instance de l'application si elle est en cours
            pgrep -f 'geolocation_api.jar' && pkill -f 'geolocation_api.jar' || echo "No running instance to stop."

            # Démarrer la nouvelle version de l'application avec les informations de connexion MySQL
            setsid nohup java -jar /home/ubuntu/geolocation_api.jar > /home/ubuntu/geolocation_api.log 2>&1 &

            # Pause pour permettre le démarrage de l'application
            sleep 5
