name: CI/CD for Spring Boot Application with MySQL Connection

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: geo_location
        options: "--name=mysql_master --health-cmd=\"mysqladmin ping -h localhost\" --health-interval=10s --health-timeout=5s --health-retries=3"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Verify JAR file
        run: |
          if [ -f "target/geolocation_api-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file exists. Proceeding with SCP transfer."
          else
            echo "JAR file not found! Check Maven build step."
            exit 1
          fi

      - name: Upload JAR and Config Files via SCP with SSH Key Authentication
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.204.227.9
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          source: |
            target/geolocation_api-0.0.1-SNAPSHOT.jar
            src/main/resources/application.yml  # Assurez-vous de copier application.yml
          target: "/home/ubuntu/"
          rm: true  # Supprime l'ancienne version avant de transférer la nouvelle

